apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "outline.fullname" . }}-configmap
  labels:
    {{- include "outline.labels" . | nindent 4 }}
data:
  DATABASE_URL: {{ include "outline.database.host" . | quote }}
  REDIS_URL: {{ include "outline.redis.host" . | quote }}