apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.fullname" . }}-secret
  labels:
    {{- include "outline.labels" . | nindent 4 }}
type: Opaque
data:
  # https://stackoverflow.com/a/68807258/4394750
  
  SECRET_KEY: {{ required "missing secretKey. You should use `openssl rand -hex 32`" .Values.env.secretKey | b64enc | quote }}
  UTILS_SECRET: {{ required "missing utilsSecret. You should use `openssl rand -hex 32`" .Values.env.utilsSecret | b64enc | quote }}

  {{ include "outline.utils.secret_if" (list "AWS_ACCESS_KEY_ID" (.Values.aws).accessKeyId) }}
