apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.fullname" . }}-secret
  labels:
    {{- include "outline.labels" . | nindent 4 }}
type: Opaque
data:
  # https://stackoverflow.com/a/68807258/4394750
  
  SECRET_KEY: {{ include "common.secrets.passwords.manage" (dict "secret" (printf "%s-secret" (include "common.names.fullname" .)) "key" "SECRET_KEY" "providedValues" (list "secretKey") "length" 32 "context" $) }}
  UTILS_SECRET: {{ include "common.secrets.passwords.manage" (dict "secret" (printf "%s-secret" (include "common.names.fullname" .)) "key" "UTILS_SECRET" "providedValues" (list "utilsSecret") "lenght" 32 "context" $) }}

  AWS_ACCESS_KEY_ID: {{ include "outline.s3.accessKeyIDKey" . | quote }}
  AWS_SECRET_ACCESS_KEY: {{ include "outline.s3.secretAccessKeyKey" . | quote }}
